server:
  port: 8080
  servlet:
    context-path: /api/test

spring:
  application:
    name: k8s

result:
  name: "ЮЗИК"

---
spring:
  config:
    activate:
      on-profile: prod

result:
  name: ${FIRST_NAME}